### ISSUE TITLE
Multiple identical databases

### ISSUE THREAD

**Issue by mr** [mitsuhiko/flask-sqlalchemy#139]
Currently there seems to be no nice way to have more than one identical database. For instance:

In __init__.py:
<pre><code>
db1 = SQLAlchemy(app)
db2 = SQLAlchemy(app)
</code></pre>

In models.py:
<pre><code>
class Table1(db1.Model):
    __tablename__ = 'TableName'
    __bind_key__ = 'bind1'
    col = db1.Column(db1.Integer)

class Table2(db2.Model):
    __tablename__ = 'TableName'
    __bind_key__ = 'bind2'
    col = db2.Column(db2.Integer)
</code></pre>

This is the only way i can really see to make 2 databases that are the same. It would be nice if there was a way to do this without having two separate metadata instances. Possibly even a way to do some inheritance on the classes.

**Comment by torotil** [comment]
There is at least one valid use-cases for that: Use one-backend for low-latency user interaction and another (read-only) connection for calculating expensive reports. This would mean two database-connections using the same set of models.

**Comment by brunsgaard** [comment]
I am right now sitting in the situation where I am looking at this example.. I have been looking at the flask-sqlalchemy code and I dont think there is any easy way to achieve what you want. I think I will take the code from  
https://github.com/myevan/flask_server/blob/master/examples/flask_sqlaclhemy_binding_master_slave.py

I think the whole bind system in flask-sqlalchemy should be replaced by a more sophisticated solution, there follow the ideas from this post http://techspot.zzzeek.org/2012/01/11/django-style-database-routers-in-sqlalchemy. But for now the code from @myevan in the best option in my opinion.

**Comment by brunsgaard** [comment]
Now I have a solution there works for me:)  Thanks go to @trustrachel for this (gist)[https://gist.github.com/trustrachel/6828122].

Hope some of your guys find it usefull.

```
from .ext.flask_ses import SES
from .ext.flask_ocmg_stateservice import StateService
from flask_ocid import Ocid, OcidException
from flask.ext.sqlalchemy import SQLAlchemy as SQLAlchemyBase
from flask.ext.sqlalchemy import get_state
from flask_jsonschema import JsonSchema
import sqlalchemy.orm as orm
from functools import partial


ocid = Ocid()
ses = SES()
jsonschema = JsonSchema()
stateservice = StateService()


class RoutingSession(orm.Session):

    def __init__(self, db, autocommit=False, autoflush=False, **options):
        self.app = db.get_app()
        self._model_changes = {}
        orm.Session.__init__(
            self,
            autocommit=autocommit,
            autoflush=autoflush,
            bind=db.engine,
            binds=db.get_binds(self.app),
            **options
        )

    def get_bind(self, mapper=None, clause=None):

        try:
            state = get_state(self.app)
        except (AssertionError, AttributeError, TypeError) as err:
            self.app.logger.error(
                "Unable to get Flask-SQLAlchemy configuration."
                " Outputting default bind. Error:" + err)
            return orm.Session.get_bind(self, mapper, clause)

        # If there are no binds configured
        # connect using the default SQLALCHEMY_DATABASE_URI
        if state is None or not self.app.config['SQLALCHEMY_BINDS']:
            self.app.logger.error(
                "Connecting -> DEFAULT. Unable to get Flask-SQLAlchemy"
                " bind configuration. Outputting default bind.")
            return orm.Session.get_bind(self, mapper, clause)

        # Writes go to the master
        elif self._flushing:  # we who are about to write, salute you
            self.app.logger.debug("Connecting -> MASTER")
            return state.db.get_engine(self.app, bind='master')

        # Everything else goes to the slave
        else:
            self.app.logger.debug("Connecting -> SLAVE")
            return state.db.get_engine(self.app, bind='slave')


class SQLAlchemy(SQLAlchemyBase):

    def create_scoped_session(self, options=None):
        if options is None:
            options = {}
        scopefunc = options.pop('scopefunc', None)
        return orm.scoped_session(
            partial(RoutingSession, self, **options), scopefunc=scopefunc
        )

db = SQLAlchemy(session_options={'autocommit': True})
```

**Comment by trustrachel** [comment]
Awesome! I'm glad it was helpful. :+1:

**Comment by brunsgaard** [comment]
@trustrachel whay about queries such at

    db.session.query(NB).filter(NB.nid.in_(expired)).\
        update({NB.seen: True}, synchronize_session=False)

I am told I am in a read-only transaction block.. any ideas?

**Comment by christopher-abastar** [comment]
Hello, 

I'm trying to implement this master/slave feature in flask-sqlchemy, but after integrating it throws some random error all over the place. One of the error was .

  File "/usr/home/cmabastar/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 573, in get
    value = state._load_expired(state, passive)
  File "/usr/home/cmabastar/env/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 480, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/usr/home/cmabastar/env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 660, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
sqlalchemy.orm.exc.ObjectDeletedError: Instance '<User at 0x80c779748>' has been deleted, or its row is otherwise not present.

The API Idid never deleted anything all it was doing was some db.session.commit() and some db.session.flush() .  autocommit = False, and autoflush = True are set it in btw.

**Comment by brunsgaard** [comment]
@christopher-abastar, would you mind formatting your post, It seems so rude to me when people pollute threads with lazy posts.

**Comment by christopher-abastar** [comment]
@brunsgaard sorry apologize for that, post editted.

**Comment by christopher-abastar** [comment]
Hello, 

I think i found out the problem. after researching a couple of days, i found out it was due to my master/slave replica lag.  After doing a db.session.commit() on my models, there is a chance that data is not yet replicated in the slave thus throwing an error. 

For the solution, django has some a solutions and they call it db pinning. When the orm tries to write to the master, the succeeding reads are forced to use master and not the slave (say, 2 seconds).


Sources: 
* http://www.javaworld.com/article/2362947/architecture-scalability/expert-interview-how-to-scale-django.html

* https://github.com/jbalogh/django-multidb-router#pinningmasterslaverouter

**Comment by davidism** [comment]
@brunsgaard shows the correct way to do this: implement the session you need and override `create_session`.  This will change slightly in the future, the custom session class can be passed to `__init__`, and will be documented better.

**Comment by fishpen0** [comment]
We are migrating to AWS aurora and it definitively uses different endpoints for reading and writing to distribute read load among several hosts and eliminate performance degradation in reads when writes are heavy.  While the above solution is a great workaround, it would be nice for flask-sqlalchemy to support this out of the box.
