### ISSUE TITLE
InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied

### ISSUE THREAD

**Issue by dantezhu** [mitsuhiko/flask-sqlalchemy#151]
in the latest version flask_sqlalchemy, the exception msg is:
<code>
Traceback (most recent call last):
  File "/data/release/harem/views/frontend.py", line 248, in show_users_order_by_level
    paginate(page_num, current_app.config['ARENA_USER_COUNT_PER_PAGE']*3)
  File "/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 414, in paginate
    total = self.order_by(None).count()
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 50, in generate
    assertion(self, fn.func_name)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 402, in _no_limit_offset
    % (meth, meth)
InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a  Query, call from_self() first.  Other
wise, call order_by() before limit() or offset() are applied.
</code>

my code is:
<code>
pgnt = User.query.limit(current_app.config['ARENA_USER_MAX_COUNT']).\
       paginate(page_num, current_app.config['ARENA_USER_COUNT_PER_PAGE'])

</code>

but in the old version of flask_sqlalchemy, It works well.
so I compare the two versions, find this code:
<code>
        # No need to count if we're on the first page and there are fewer
        # items than we expected.
        if page == 1 and len(items) < per_page:
            total = len(items)
        else:
            total = self.order_by(None).count()
</code>

in the old version, there is no such code.

so I dont know why to add this code in new version, is it a bug?

**Comment by xgdgsc** [comment]
I encounter such error when trying to implement function that first order_by time, then do the pagination. Currently I use: 
```
 Table.query.order_by(Table.Timestamp).limit(500)\
        .paginate(page, POSTS_PER_PAGE, False).items
```
which gives the error.

Can anyone tell me what is the right approach to do such a thing for now?

**Comment by davidism** [comment]
The issue was introduced [here][1], where `order_by` is reset to count the total items.  This is a small optimization so that the database doesn't need to compute the order a second time when counting.

SQLAlchemy does not allow `order_by` after `limit`/`offset` in the same query, as it could be interpreted (incorrectly) to be applying the order to the limited/offset results, rather than the entire query.  Since you've manually applied a limit, SQLAlchemy complains when paginate tries to change the order.

Realistically, you should not apply a limit manually if you are going to use `paginate`, since that is the job of paginate.  Applying a limit is redundant.  The error message suggests an alternate solution, if you really want to apply a limit: use `from_self()` before calling `paginate`.

@immunda I think this issue can be closed.

[1]: https://github.com/mitsuhiko/flask-sqlalchemy/commit/4bcd2337f505580b8e62bce91ff17b981e7938a4

**Comment by xgdgsc** [comment]
@davidism Thanks. I removed the limit and it is fine for me.

**Comment by immunda** [comment]
:+1:
