### ISSUE TITLE
query.filter_by returns list for primary_key

### ISSUE THREAD

**Issue by PatrickEGorman** [mitsuhiko/flask-sqlalchemy#260]
More of a suggestion than an issue.  If you use filter_by on the primary_key it returns a list even though there is only one object with a primary key.

**Comment by bastianh** [comment]
This makes no sense. filter_by does not return a list or an object but just modifies the sql query.

 If you just want one item you can use .first().

Even if this would be an issue, it would not be a flask-sqlalchemy issue since filter_by is part of sqlalchemy. (http://docs.sqlalchemy.org/en/rel_0_9/orm/query.html#sqlalchemy.orm.query.Query.filter_by)

**Comment by PatrickEGorman** [comment]
To be honest I'm just starting out on all this so I hope you guys won't be too critical.  Thanks for the honest reply though.  I suppose somebody should close this issue

**Comment by bastianh** [comment]
Sorry if I sounded rude .. it was not my intention ;9

**Comment by PatrickEGorman** [comment]
Sorry if I sounded ignorant it was not my intention haha.  You're fine

**Comment by immunda** [comment]
Hey Patrick, thanks for your feedback, but this isn't really an issue with the library, as @bastianh mentioned.

Feel free to pop onto #pocoo on freenode if you have any questions!
