### ISSUE TITLE
poor performance of pagination under large dataset

### ISSUE THREAD

**Issue by wormcc** [mitsuhiko/flask-sqlalchemy#272]
when i use paginate under a large dataset, the  performance of pagination is very poor? is it caused by the count() func here https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L481 ?my database is mysql

**Comment by immunda** [comment]
Hi @wormcc. How large are we talking here?

**Comment by wormcc** [comment]
Thanks for your reply, my dataset is include among 30 thousand items.

 <pre>
**extensions.py**
from flask.ext.sqlalchemy import SQLAlchemy
db = SQLAlchemy()
...


**models.py**
from .extensions import db

class Info(db.Model):
    \__tablename\__ = 'info'
     ...
    @classmethod
    def get_to_edit_list(cls, page=1, per_page=20):
        edit_list = cls.query.filter(Info.verify == 2).\
             order_by(Info.create_time.desc()).paginate(page, per_page, True)
        return edit_list

**template file**
{% for item in to_edit_list.items %}
...
{% endfor %}
</pre>
my plantform info
<pre>
model name	: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
cpu MHz		: 768.000
cache size	: 3072 KB

MemTotal:        7877408 kB


ubuntu 14.04 distribution
python 2.7.9
</pre>
any problems above? @immunda Thanks angin!

**Comment by xen** [comment]
I don't know how big your dataset is, and how far you paginate through it, but generally speaking OFFSET command is terrible solution for pagination. Inside database server compute data from the start, but doesn't send to the client until go through all that needed to be skipped.

Much better to use cursor with sort and item ids, because then index is used for query optimization. First of all add index to `verify ` and `create_time` columns, after add additional parameter to query. This is not tested, but I think you can get an idea:

```
    @classmethod
    def get_to_edit_list(cls, last_id, page=1, per_page=20):
        edit_list = cls.query.filter(Info.verify == 2, Info.id>=last_id).\
             order_by(Info.create_time.desc()).limit(per_page)
        return edit_list
```

**Comment by immunda** [comment]
Fuller discussion over in #281
