### ISSUE TITLE
_should_set_tablename is problematic

### ISSUE THREAD

**Issue by ThiefMaster** [mitsuhiko/flask-sqlalchemy#349]
It runs at import time and ends up accessing _all_ attributes on the model classes.

My base model class has a class-level property like this:

```
@classproperty
@classmethod
def has_rows(cls):
    """Checks if the underlying table has any rows.

    This is done in an efficient way and should preferred over
    calling the `count` method unless you actually care about
    the exact number of rows.
    """
    from indico.core.db import db
    # we just need one "normal" column so sqlalchemy doesn't involve relationships
    # it doesn't really matter which one it is - it's never even used in the query
    pk_col = getattr(cls, inspect(cls).primary_key[0].name)
    return db.session.query(db.session.query(pk_col).exists()).one()[0]
```

Updating to 2.1 breaks since the local import inside that method ends up being executed as import time again; also, accessing it would trigger SQL if it didn't fail.

I think in this case I'll simply convert it to a normal classmethod, but I wonder if there are any other cases that might break...

**Comment by jeffwidman** [comment]
That makes more sense... couldn't figure out why my classproperty (looks similar to yours) was breaking:

    from app import db
    db.session.query(db.exists([GearCategory.id]).where(GearCategory.id == parent_id)).scalar()

**Comment by davidism** [comment]
I probably caused this while extending the tablename generation, although all tests passed at the time.  If you could create a test case demonstrating this, that would be helpful.

**Comment by vToMy** [comment]
I believe I might have a solution (change to the for loop in `_should_set_tablename`):
```
    for base in bases:
        for base_mro in base.__mro__:
            if '__tablename__' in base_mro.__dict__ or '__table__' in base_mro.__dict__:
                return False
            for key, value in base_mro.__dict__.items():
                column = None
                if isinstance(value, sqlalchemy.Column):
                    column = value
                elif isinstance(value, declared_attr):
                    column = getattr(base_mro, key)
                if column is not None and column.primary_key:
                    return True
    return False
```

The changes are:
1) No more direct access to `__table__` and `__tablename__` as this causes `SAWarning: Unmanaged access of declarative attribute __tablename__` in unmapped classes (mixins and custom declarative base). Instead of using `hasatttr` which in turn calls `getattr` which invokes said warning, I'm iterating the `__mro__` and checking if those attributes exists in their `__dict__`
2) As for the columns - instead of checking each attribute in the model I'm only iterating `Column` and `declared_attr_`, thus not calling any unwanted properties. Ideally I'd have like to use `sqlalchemy.inspect(model).columns` but it only supports mapped models (so no mixins and declarative base).
3) Return `False` after the loop. I see no return value in the original implementation, and this looks like a miss... (though it works without it since it returns `None` which is treated like `False`, it's not good practice)

Tests are passing.
I can offer a pull requests, but I'd like to get some feedback as I'm less familiar with the internals of this library, so I want to make sure I haven't missed anything.

**Comment by davidism** [comment]
@vToMy unfortunately, the `getattr(base_mro, key)` still raises the "unmanaged access" warning, which I'd like to eliminate.

I'm still experimenting.

**Comment by vToMy** [comment]
How so? The code explicitly checks for `__table__` and `__tablename__` before running the loop.
Unless there are some other attributes?

**Comment by davidism** [comment]
Getting any declared attr, which your code does, before the class is mapped (which is when this runs), causes the warning.

**Comment by davidism** [comment]
The quickest, and possibly only, fix for this is to just remove handling declared attrs, which 2.0 didn't do anyway. It would make some mixin patterns not work automatically, but I'm ok with that.

I could also add some assumptions like "if there's a declared attr called `id` or `pk`, assume it's a primary key" without actually evaluating the attr.

**Comment by vToMy** [comment]
How about adding table name as a declared attribute, and lazily evaluate it after the mapping?

**Comment by ThiefMaster** [comment]
Radical suggestion: Use the major version jump to 3.0 to get rid of autogenerated table names. As soon as you start using Foreign Keys where you usually reference tables/columns using string names it's extremely messy since now you have a hardcoded name for the table there even though the name of the actual table is auto-generated.

**Comment by davidism** [comment]
I don't think I'm willing to completely remove it.

The autogeneration is really handy for quick projects and examples, and I've (for better or worse) managed to write large applications using it. I also think it's intuitive to expect the tablename to be generated since the column names are.

The use of hard coded tablenames in foreign keys can be avoided either with careful ordering of class definitions or with declared attrs, and having the tablenames and foreign keys change (and generate migrations) when refactoring is useful.

Using a declared attr for tablename presents its own issues. Single table inheritance no longer works unless you set `__tablename__ = None`. If you set a tablename explicitly in a parent class, all future tables loose the declared attr and must set their names manually.

**Comment by vToMy** [comment]
I've experimented a bit and found a nice solution with declared attributes:

```
class Model(object):
    _tablename = None

    @declared_attr.cascading
    def __tablename__(cls):
        if '_tablename' in cls.__dict__:
            return cls._tablename

        if _should_set_tablename(cls.__bases__, cls.__dict__):
            def _join(match):
                word = match.group()
                if len(word) > 1:
                    return ('_%s_%s' % (word[:-1], word[-1])).lower()
                return '_' + word.lower()

            cls._tablename = _camelcase_re.sub(_join, cls.__name__).lstrip('_')

        if cls._tablename is not None:
            return cls._tablename
        else:
            raise AttributeError
```

I moved the code from `_BoundDeclarativeMeta.__new__` to the `Model` class.
Using `declared_attr.cascading` solves the single table inheritance issue, since the attribute is being declared for each class in the hierarchy.

As for setting individual table names, this little magic solves it:
```
class _BoundDeclarativeMeta(DeclarativeMeta):
    def __new__(cls, name, bases, d):
        tablename = d.pop('__tablename__', None)
        if tablename:
            d['_tablename'] = tablename

        return DeclarativeMeta.__new__(cls, name, bases, d)
```

I managed to get all tests passing (+1 extra test I added for setting custom parent table).
I just had to change single test custom model class to inherit from `Model` which it should have in the first place.

**Comment by davidism** [comment]
Hadn't heard of `cascading`, thanks, I'll try it out.
