### ISSUE TITLE
Looking for a way for pagination integration with swift/ios... 

### ISSUE THREAD

**Issue by rlam3** [mitsuhiko/flask-sqlalchemy#399]
Looking for a way for pagination integration with swift/ios... 

I recently saw the following post: https://www.sitepoint.com/paginating-real-time-data-cursor-based-pagination/

Does Flask-sqlalchemy support this? If not, how should one go about using the orm to do this sort of cursor based pagination so that it can be used in an API for pagination.

**Comment by davidism** [comment]
You can use pagination with anything, it's not swift specific.  I'm not sure how the link is related either.  Flask-SQLAlchemy is not going to support every pagination scheme under the sun, but it does support anything that SQLAlchemy does.  There is nothing stopping you from implementing whatever api you want in order to describe pagination.
