### ISSUE TITLE
MariaDB defaults cause `2013, 'Lost connection to MySQL server during query'`

### ISSUE THREAD

**Issue by nickw444** [mitsuhiko/flask-sqlalchemy#401]
Whilst not directly an issue with this library, it might be worth noting that the default that is chosen for `SQLALCHEMY_POOL_RECYCLE` when using MariaDB as a drop in replacement for MySQL causes a hard to debug connection error.

Comparing the defaults between MYSQL and MariaDB we find:
## MySQL `5.7.12`:

```
mysql> SHOW GLOBAL VARIABLES LIKE "wait_timeout";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.00 sec)
```
## MariaDB `10.1.14-MariaDB-1~xenial`

```
MariaDB [(none)]> SHOW GLOBAL VARIABLES LIKE "wait_timeout";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 600   |
+---------------+-------+
1 row in set (0.00 sec)

root@c554e4589da8:/# cat /etc/mysql/my.cnf | grep timeout
connect_timeout     = 5
wait_timeout        = 600
```

Flask-SQLAlchemy defaults to using a 2 hour recycle time (`7200 seconds`), which obviously is too long for MariaDB's default `600 second` timeout, however is a reasonable value for MySQL, which defaults to `28800 seconds`. 

Personally, I think it might be worth noting this in the [configuration keys](http://flask-sqlalchemy.pocoo.org/2.1/config/#configuration-keys) page of the documentation for the `SQLALCHEMY_POOL_RECYCLE` key, since that is the first place users are generally directed when searching the issue.

**Comment by davidism** [comment]
Is there a way to detect Maria vs MySQL during `apply_driver_hacks`?

**Comment by nickw444** [comment]
Unless the user provides a mariadb specific database URI that we re-write to MySQL, I can't think of a way. Plus this also takes away from mariadb being a drop in replacement. I suppose we could run the select query above to calculate the timeout on initialisation? 

But I think that's putting too much responsibility into this library. It really should come down to user configuration.

**Comment by immunda** [comment]
Whilst a valid suggestion @nickw444, I think you're right that it's better to avoid confusing the issue with a `mariadb` URI.

It seems that short of setting the default timeout to `600` seconds (which would actually solve some issues we get with users having timeout issues due to DB providers settings shorter timeouts), documenting this behaviour does seem the way to go.

Would you be up for submitting a PR @nickw444 ?

**Comment by nickw444** [comment]
PR Created. Cheers

**Comment by nickw444** [comment]
Closing as I just realised this PR had been merged.

**Comment by davidism** [comment]
I just installed MariaDB on Arch Linux, and the default is 28800, the same as MySQL. Lending further difficulty to detecting this, since it's down to the distro, not the database, what the defaults are. Might be better to mention defaults in general rather than distinguishing between MySQL and MariaDB.
