### ISSUE TITLE
RuntimeError: application not registered on db instance and no application bound to current context

### ISSUE THREAD

**Issue by damonchen** [mitsuhiko/flask-sqlalchemy#410]
When I use 

```python
db = SQLAlchemy()
db.init_app(app)
```

will raise the exception:
`RuntimeError: application not registered on db instance and no application bound to current context`

but `db = SQLAlchemy(app)` is ok

**Comment by davidism** [comment]
An app is only bound to the extension if it is passed directly, which is a shortcut when you're not using the app factory pattern.  Otherwise, you can only use most of it within an app context so that `current_app` is populated.  If you're in a view, this is is invisible, but if you're not you need to push a context:

~~~python
with app.app_context():
    db.session.query(...)
~~~
