### ISSUE TITLE
[API request] Proxy to current Flask-SQLAlchemy instance

### ISSUE THREAD

**Issue by Code-ReaQtor** [mitsuhiko/flask-sqlalchemy#501]
Hi,

It seems that there isn't an easy way to access the current Flask-SQLAlchemy instance from separate python files (e.g. Pluggable Views).

Will there be a plan for a proxy similar to Flask's [current_app](http://flask.pocoo.org/docs/0.12/api/#flask.current_app) and Flask-Login's [current_user](https://flask-login.readthedocs.io/en/latest/#flask_login.current_user)?

Thanks!

**Comment by davidism** [comment]
This shouldn't be necessary. `db` itself isn't a context local, it uses `current_app` behind the scenes. If you use deferred init (`init_app`), you can import `db` wherever you need it and assume it's registered.

**Comment by ThiefMaster** [comment]
This actually forces you to use a somewhat clean structure. For example, you could have `yourpkg/db.py` containing only the `db = SQLAlchemy()` (and whatever other import-time stuff you do with it, such as setting up a constraint/index naming scheme).

Then, in the module containing your app factory (let's say `yourpkg/factory.py`) you import `db` and - inside your app factory - call `db.init_app()`.

Since your blueprints should be imported from within your app factory (ie not top-level imports) any of the files only imported from the files containing your blueprints should have no problem to import `yourpkg.db`.
