### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by crhuber** [mitsuhiko/flask-sqlalchemy#582]
I have a cron job that connects to the database once a day and sends out email. Every second day I get this message:

> OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')

In my configuration i have the following settings

```
    SQL_ALCHEMY_POOL_RECYCLE = 50

    SQLALCHEMY_POOL_SIZE = 100
```

Im using  MySQL:5.6 in a Docker Container https://hub.docker.com/_/mysql/

Ive read so many stackoverflow articles on how to fix this but no combination of pool size or pool recycle seems to fix it.  Is this a bug or a configuration problem?

**Comment by davidism** [comment]
Probably your process only acquires a connection when it starts. The recycle is for the pool, not for active connections. Only acquire a connection when you need it, then close it. This is typically not an issue in Flask because requests don't last that long.

However, this tracker is not the place to get help with these issue. Please use Stack Overflow. Be sure to include a [Minimal, Complete, and Verifiable Example](https://stackoverflow.com/help/mcve).

**Comment by zmarffy** [comment]
I believe this is an issue with the extension or it's something the project isn't hitting, at least. How is one to acquire a connection only when they need it when it comes to a long-running Celery task, for example, which would use the connection from the request? Maybe I'm missing something super obvious but I don't see an easy way with this extension to do such a thing.
