### ISSUE TITLE
mysql pool recycle default

### ISSUE THREAD

**Issue by asergeyev** [mitsuhiko/flask-sqlalchemy#91]
there is default for mysql driver in flask-sqlalchemy
    options.setdefault('pool_recycle', 7200)

Most servers will timeout client connection in 1 hour IMO it's better to use this as a default value and let people change it to longer times when appropriate.

(....there is another caveat right now - if your mysql server got restarted there is nothing that would catch exception and try to reconnect to serve current request, I wonder if that exception would be possible to catch in lib, not inside of the application code)

**Comment by kkamkou** [comment]
+1

**Comment by davidism** [comment]
According to the [Flask-SQLAlchemy docs][1] and the [SQLAlchemy docs][2], MySQL recycles connections every *8* hours by default, and Flask-SQLAlchemy sets this to *2* hours.  I've seen plenty of questions about MySQL timeouts on SO, but I'd be more inclined to change this if you could point to a definitive statement that the default is *1* hour.

[SQLAlchemy][3] also describes some ways that connections can be invalidated.  I'm not sure if these sorts of things should be worked into Flask-SQLAlchemy.

[1]: http://flask-sqlalchemy.pocoo.org/2.0/config/?highlight=mysql
[2]: http://docs.sqlalchemy.org/en/rel_1_1/dialects/mysql.html#connection-timeouts
[3]: http://docs.sqlalchemy.org/en/latest/core/pooling.html#dealing-with-disconnects

**Comment by immunda** [comment]
The defaults for both `interactive_timeout` and `wait_timeout` are 8 hours. I appreciate that some folks may have providers with unusual DB configurations, but I don't think that's the responsibility of this library to solve, as it wouldn't provide a general solution.

I've also read through that SO post and whilst valid, without a running and complete configuration to be tested against, there's no way to determine whether that particular problem is even caused by this.
