### ISSUE TITLE
Teardown app context vs. request context

### ISSUE THREAD

**Issue by alexex** [mitsuhiko/flask-sqlalchemy#99]
According to L672 flask-sqlalchemy uses teardown_appcontext if available and not teardown_requestcontext. I would actually like to know what thought was behind this, as the sqlalchemy docs suggest to close/remove/rollback the session after every request (see http://docs.sqlalchemy.org/en/rel_0_7/orm/session.html#lifespan-of-a-contextual-session).

In my opinion this can lead to problems with pool_recycle as not all connections are always returned to the pool (at least my sqlalchemy log looked like it) and so the pool won't be recycled. But I might be wrong.

**Comment by georgexsh** [comment]
> When handling a request, the app context has a similar lifecycle to the request context

@mgax I think it is not true, `RequestContext.pop` will not pop app context stack if request is handled within a exists app context

**Comment by ngaya-ll** [comment]
Flask's own [documentation](http://flask.pocoo.org/docs/0.12/patterns/sqlalchemy/) suggests using `teardown_appcontext`.

**Comment by lepture** [comment]
@davidism I think we should do `session.remove()` in `teardown_request`, so that session in every request is clean.

**Comment by davidism** [comment]
Commented on this in https://github.com/mitsuhiko/flask-sqlalchemy/issues/379#issuecomment-269878367.

> I'm going to need an example of how to run Flask in such a way that the same app context is reused for multiple requests (not for multiple manual request contexts within a single app context or test, but for actual requests). I can't reproduce this error and using the app context should be correct. The app context is for global app state during an interaction (such as a request or cli command).

**Comment by lepture** [comment]
@davidism Yes, you are right. App context is the same as request context.

**Comment by georgexsh** [comment]
oh, I see, since I am using Flask-Script as entry point, a new app ctx object will be pushed to stack at the very beginning, then there will no new app ctx object be created when handling new request, all within the same outermost app context, as a result,`teardown_appcontext` wont be triggered pre-request.
stating app context is the same as request context sounds wired to me, if this is true, why bother to distinguish two context stack, apparently they are not.
nevertheless, if we agree that database transaction should be isolated pre request, then teardown_request should be used here.

**Comment by georgexsh** [comment]
oh, I see, since I am using Flask-Script as entry point, a new app ctx object will be pushed to stack at the very beginning(ref [1]), then there will no new app ctx object be created when handling new request(ref [2]), all within the same outermost app context, as a result,`teardown_appcontext` wont be triggered pre-request(ref [3]).
stating app context is the same as request context sounds wired to me, if this is true, why bother to distinguish two context stack, apparently they are not.
nevertheless, if we agree that database transaction should be isolated pre request, then teardown_request should be used here.

[1]: https://github.com/smurfix/flask-script/blob/master/flask_script/commands.py#L215
[2]: https://github.com/pallets/flask/blob/master/flask/ctx.py#L316
[3]: https://github.com/pallets/flask/blob/master/flask/ctx.py#L380
